databases:
  - name: lobotomynews
    plan: free
    databaseName: lobotomynews
    user: lobotomynews

services:
  - type: web
    plan: free
    name: lobotomynews
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn init.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lobotomynews
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4